### ISSUE TITLE
Unable to build docker Image

### ISSUE THREAD

**Issue by rahulmysore23** [signintech/gopdf#151]
Dockerfile - 
```
FROM golang:1.12.1

RUN mkdir /build
COPY main.go /build
WORKDIR /build
RUN ls

RUN go mod init imgpdf
RUN go run main.go
```

main.go contains the sample code from the readme. 

Error when I try to build the docker image - 
```
Step 7/7 : RUN go run main.go
 ---> Running in 6fcd53339dd4
go: finding github.com/signintech/gopdf v0.9.12
go: downloading github.com/signintech/gopdf v0.9.12
go: extracting github.com/signintech/gopdf v0.9.12
go: finding github.com/phpdave11/gofpdi v1.0.8
go: finding github.com/pkg/errors v0.8.1
go: downloading github.com/phpdave11/gofpdi v1.0.8
go: extracting github.com/phpdave11/gofpdi v1.0.8
go: downloading github.com/pkg/errors v0.8.1
go: extracting github.com/pkg/errors v0.8.1
# github.com/signintech/gopdf
/go/pkg/mod/github.com/signintech/gopdf@v0.9.12/gopdf.go:1215:10: undefined: errors.Unwrap
/go/pkg/mod/github.com/signintech/gopdf@v0.9.12/gopdf.go:1271:9: undefined: errors.Unwrap
/go/pkg/mod/github.com/signintech/gopdf@v0.9.12/gopdf.go:1288:9: undefined: errors.Unwrap
The command '/bin/sh -c go run main.go' returned a non-zero code: 2
``` 

Are there any dependencies to install? What am I doing wrong here? 

Update - It works when I use golang v1.13. It still does not work with v1.12.

**Comment by oneplus1000** [comment]
**errors.Unwrap** is function on v1.13 https://blog.golang.org/go1.13-errors

**Comment by jordan-chalupka** [comment]
Minimum golang version has been added. We can close this issue
